version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

test-steps: &test-steps
  steps:
    - checkout
    - run: |
        pip install -U pip setuptools wheel
        pip install tox
        tox
    - codecov/upload:
      file: {{ coverage_report_filepath }}

jobs:
  lint:
    steps:
      - checkout
      - run: |
          pip install -U pip setuptools wheel tox
          tox -e isort,lint
    docker:
      - image: circleci/python:3.7

  dist:
    steps:
      - checkout
      - run: |
          pip install -U pip setuptools wheel tox
          python setup.py bdist_wheel
          tox -e dist --installpkg ./dist/tox_factor-*.whl
          tox -e dist
    docker:
      - image: circleci/python:3.7

  test-py37:
    <<: *test-steps
    docker:
      - image: circleci/python:3.7
    environment:
      TOXENV: py37

  test-py36:
    <<: *test-steps
    docker:
      - image: circleci/python:3.6
    environment:
      TOXENV: py36

  test-py35:
    <<: *test-steps
    docker:
      - image: circleci/python:3.5
    environment:
      TOXENV: py35

  test-py27:
    <<: *test-steps
    docker:
      - image: circleci/python:2.7
    environment:
      TOXENV: py27


workflows:
  version: 2
  test:
    triggers:
      - schedule:
          # 8/9 AM PST/PDT every Monday
          cron: "0 16 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - lint
      - dist:
          requires:
            - lint

      - test-py37:
          requires:
            - lint

      - test-py36:
          requires:
            - lint

      - test-py35:
          requires:
            - lint

      - test-py27:
          requires:
            - lint
