version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4


aliases:
  - &environ
    run:
      name: install dependencies & setup environment
      command: |
        virtualenv venv
        venv/bin/pip install -U pip setuptools wheel tox

  - &test-steps
    steps:
      - checkout
      - *environ
      - run: venv/bin/tox
      - codecov/upload:
          file: .coverage

jobs:
  lint:
    steps:
      - checkout
      - *environ
      - run: venv/bin/tox -e isort,lint
    docker:
      - image: circleci/python:3.7

  dist:
    steps:
      - checkout
      - *environ
      - run: |
          venv/bin/python setup.py bdist_wheel
          venv/bin/tox -e dist --installpkg ./dist/tox_factor-*.whl
          venv/bin/tox -e dist
    docker:
      - image: circleci/python:3.7

  test-py37:
    <<: *test-steps
    docker:
      - image: circleci/python:3.7
    environment:
      TOXENV: py37

  test-py36:
    <<: *test-steps
    docker:
      - image: circleci/python:3.6
    environment:
      TOXENV: py36

  test-py35:
    <<: *test-steps
    docker:
      - image: circleci/python:3.5
    environment:
      TOXENV: py35

  test-py27:
    <<: *test-steps
    docker:
      - image: circleci/python:2.7
    environment:
      TOXENV: py27


workflows:
  version: 2
  commit: &test-workflow
    jobs:
      - lint
      - dist:
          requires:
            - lint

      - test-py37:
          requires:
            - lint

      - test-py36:
          requires:
            - lint

      - test-py35:
          requires:
            - lint

      - test-py27:
          requires:
            - lint

  weekly:
    <<: *test-workflow
    triggers:
      - schedule:
          # 8/9 AM PST/PDT every Monday
          cron: "0 16 * * 1"
          filters:
            branches:
              only:
                - master
